"""Run once on PUL-095 baseline blends, from repository root with Blender CLI.
Atlas inputs generated by build_graphics.py. Existing contracts remain unchanged.
"""
import bpy,bmesh,json,math,sys
from pathlib import Path
from mathutils import Vector
ROOT=Path.cwd(); OUT=ROOT/'docs/evidence/PUL-095'
bpy.context.preferences.filepaths.save_version=0
budget={}
def replace_image(name,path):
 old=bpy.data.images[name]
 img=bpy.data.images.load(str(path)); img.name=name+'_new'; img.pack()
 old.user_remap(img); bpy.data.images.remove(old); img.name=name
 return img

def quad(ob,coords,uvs,matidx):
 bm=bmesh.new(); bm.from_mesh(ob.data); layer=bm.loops.layers.uv.verify()
 f=bm.faces.new([bm.verts.new(p) for p in coords]); f.material_index=matidx
 for l,uv in zip(f.loops,uvs): l[layer].uv=uv
 bm.to_mesh(ob.data); bm.free()
def patch(ob,center,u,v,cell,matidx):
 c,u,v=Vector(center),Vector(u)/2,Vector(v)/2
 coords=[c-u-v,c+u-v,c+u+v,c-u+v]
 x=cell*.25
 quad(ob,coords,[(x,0),(x+.25,0),(x+.25,.25),(x,.25)],matidx)
def mesh(name,parent,coll,mat):
 m=bpy.data.meshes.new(name); m.materials.append(mat)
 o=bpy.data.objects.new(name,m); o.parent=parent; coll.objects.link(o); return o

def count(coll):
 return sum(sum(len(p.vertices)-2 for p in o.data.polygons) for o in coll.all_objects if o.type=='MESH')
def export(coll,path,limit):
 # Use the exact repository validator/exporter with the selected collection.
 ns={'__file__':str(ROOT/'tools/blender_export.py'),'__name__':'pul095_export'}
 code=(ROOT/'tools/blender_export.py').read_text(); exec(code.rsplit('\nmain()',1)[0],ns)
 ns['EXPORT_COLLECTION']=coll.name
 old_front=bpy.data.objects.get('Anchor_Front')
 target=next(o for o in coll.all_objects if o.name.startswith('Anchor_Front'))
 if old_front and old_front!=target: old_front.name='Stored_Anchor_Front'
 target_name=target.name; target.name='Anchor_Front'
 budget[path.stem]=count(coll)
 sys.argv=['blender','--','--out',str(path),'--max-tris',str(limit)]
 ns['main']()
 target.name=target_name
 if old_front and old_front!=target: old_front.name='Anchor_Front'

def save(name):
 txt=bpy.data.texts.get('PUL095_update.py') or bpy.data.texts.new('PUL095_update.py')
 txt.from_string(Path(__file__).read_text())
 bpy.ops.wm.save_as_mainfile(filepath=str(ROOT/'art/blender'/f'{name}.blend'))

bpy.ops.wm.open_mainfile(filepath=str(ROOT/'art/blender/box.blend'))
replace_image('box_atlas_albedo',OUT/'tray_atlas.png'); replace_image('box_atlas_orm',OUT/'tray_orm.png')
for i,size in enumerate(('small','medium','large')):
 ob=bpy.data.objects['box_'+size]
 # More decisive M oval, same width and anchors. Keep liner area large enough for existing food.
 if size=='medium':
  for name in ('box_medium','hull_medium'):
   for vert in bpy.data.objects[name].data.vertices: vert.co.y*=.90
 b={'small':.170,'medium':.144,'large':.190}[size]
 # Secondary letter on a sloping rim tab. Free centre and all progress/badge anchors.
 patch(ob,(0,-b+.030,.112),( .115,0,0),(0,.085,.035),i,1)
 # Closed tab hull, invisible as before; prevents open-mesh yellow fill.
 hull=bpy.data.objects['hull_'+size]; bm=bmesh.new(); bm.from_mesh(hull.data)
 vs=bmesh.ops.create_cube(bm,size=1)['verts']
 for vert in vs:
  p=vert.co.copy(); vert.co=(p.x*.115,-b+.030+p.y*.085,.106+p.z*.012+p.y*.035)
 bmesh.ops.recalc_face_normals(bm,faces=bm.faces[:]); bm.to_mesh(hull.data); bm.free()
 budget['tray_'+size]=sum(len(p.vertices)-2 for p in ob.data.polygons)+sum(len(p.vertices)-2 for p in hull.data.polygons)
save('box'); export(bpy.data.collections['export'],ROOT/'godot/assets/models/items/box/box.glb',6000)

bpy.ops.wm.open_mainfile(filepath=str(ROOT/'art/blender/box_shelf.blend'))
replace_image('box_atlas_albedo',OUT/'tray_atlas.png'); replace_image('box_atlas_orm',OUT/'tray_orm.png')
coll=bpy.data.collections['export']; parent=bpy.data.objects['box_shelf']
# Existing optimized stacks retain their footprint; M follows the new silhouette.
for name in ('stack_medium','hull_medium'):
 ob=bpy.data.objects[name]
 for vert in ob.data.vertices:
  vert.co.y=(vert.co.y-.78)*.90+.78 if name.startswith('stack') else vert.co.y*.90
old=bpy.data.objects.get('labels'); bpy.data.objects.remove(old,do_unlink=True)
ob=mesh('labels',parent,coll,bpy.data.materials['atlas_box'])
for i,x in enumerate((-.51,0,.536)):
 # Front +Y. Upright plaques, immediately under each stack.
 patch(ob,(x,1.063,.245),(-.25,0,0),(0,0,.15),i,0)
 # Upward-facing duplicate: letter's baseline toward local -X, camera-facing after rack yaw.
 patch(ob,(x,.34,.313),(0,.30,0),(-.30,0,0),i,0)
save('box_shelf'); export(coll,ROOT/'godot/assets/models/stations/box_shelf/box_shelf.glb',6000)

bpy.ops.wm.open_mainfile(filepath=str(ROOT/'art/blender/counters.blend'))
replace_image('counters_atlas',OUT/'counter_atlas.png')
# Preserve existing atlas imagery in top-left quarter; remap only its original faces.
for ob in bpy.data.objects:
 if ob.type!='MESH' or not ob.data.uv_layers.active: continue
 ids=[i for i,m in enumerate(ob.data.materials) if m and m.name=='counters_atlas']
 for p in ob.data.polygons:
  if p.material_index in ids:
   for li in p.loop_indices:
    uv=ob.data.uv_layers.active.data[li].uv; uv.x*=.5; uv.y=uv.y*.5+.5

def piece(name):
 coll=bpy.data.collections.new('export_'+name); bpy.context.scene.collection.children.link(coll)
 root=bpy.data.objects.new(name,None); coll.objects.link(root)
 front=bpy.data.objects.new('Anchor_Front_'+name,None); coll.objects.link(front); front.parent=root; front.location=(0,.5,0)
 return coll,mesh(name+'_body',root,coll,bpy.data.materials['counters_atlas'])
def rect(ob,x0,x1,y0,y1,z,paper):
 uv=(.25,.20) if paper else (.75,.20)
 quad(ob,[(x0,y0,z),(x1,y0,z),(x1,y1,z),(x0,y1,z)],[uv]*4,0)
coll,ob=piece('pass_mark')
# Four separate paper/navy corner brackets, open centre. Downturned ends form a 5 cm apron
# over a counter edge; top at local 0.052, base at zero to satisfy pipeline bounds.
for sx in (-1,1):
 for sy in (-1,1):
  x0,x1=sorted((sx*.17,sx*.36)); y0,y1=sorted((sy*.18,sy*.37))
  rect(ob,x0,x1,y0,y1,.052,True)
  # Navy L on paper; broad readable strokes.
  a,b=sorted((sx*.20,sx*.33)); c,d=sorted((sy*.21,sy*.34))
  rect(ob,a,b,c,c+.055 if sy<0 else d,.053,False) if sy<0 else rect(ob,a,b,d-.055,d,.053,False)
  rect(ob,a,a+.055,c,d,.053,False) if sx<0 else rect(ob,b-.055,b,c,d,.053,False)
  # Tiny folded edge outside corner, visible side provides thickness, no raised obstacle.
  y=sy*.37; uv=(.25,.20)
  quad(ob,[(x0,y,0),(x1,y,0),(x1,y,.052),(x0,y,.052)],[uv]*4,0)
coll2,ob2=piece('pass_threshold')
# Inset tread: 4 cm buried, 1.2 cm visible. No collision, no obstruction across opening.
rect(ob2,-.45,.45,-.43,.43,.012,False)
for y in (-.36,.29): rect(ob2,-.40,.40,y,y+.07,.013,True)
for x in (-.45,.45):
 uv=(.75,.20); quad(ob2,[(x,-.43,-.04),(x,.43,-.04),(x,.43,.012),(x,-.43,.012)],[uv]*4,0)
# Replace old closed slot outlines with inset paper/navy corner marks on the modules.
for name,n in (('pass_1m',1),('pass_2m',2),('pass_3m',3),('pass_end',1)):
 body=bpy.data.objects[name+'_body']; bm=bmesh.new(); bm.from_mesh(body.data)
 dark=[i for i,m in enumerate(body.data.materials) if m.name=='mat_steel_dark']
 drop=[f for f in bm.faces if f.material_index in dark and all(v.co.z>=1.099 for v in f.verts)]
 bmesh.ops.delete(bm,geom=drop,context='FACES'); bm.to_mesh(body.data); bm.free()
 atlasidx=next(i for i,m in enumerate(body.data.materials) if m.name=='counters_atlas')
 source=bpy.data.objects['pass_mark_body']
 for k in range(n):
  cx=-n/2+.5+k
  for face in source.data.polygons:
   # Folded apron lies inside the counter; omit it from the integrated surface mark.
   if any(source.data.vertices[j].co.z<.05 for j in face.vertices): continue
   coords=[source.data.vertices[j].co+Vector((cx,0,1.048)) for j in face.vertices]
   uvs=[source.data.uv_layers.active.data[j].uv[:] for j in face.loop_indices]
   quad(body,coords,uvs,atlasidx)

save('counters')
# Original modules are exported as well because atlas UVs changed, not their shapes.
for c in list(bpy.data.collections):
 if c.name=='export' or c.name.startswith('export_'):
  root=next(o for o in c.objects if o.parent is None)
  export(c,ROOT/'godot/assets/models/furniture/counters'/f'{root.name}.glb',4500)
(OUT/'budget.json').write_text(json.dumps(budget,indent=2)+'\n')
