"""Original PUL-094 production geometry. Run Blender CLI from repo root.
Atlas generated by make_atlas.py; materials linked from the v2 library.
"""
import bpy, bmesh, math, json
from pathlib import Path
from mathutils import Vector
ROOT = Path.cwd()
OUT = ROOT/'docs/evidence/PUL-094'
DEST = ROOT/'godot/assets/models/stations/seasoning_station'
# Retain linked library and reference collection; replace export objects only.
for c in list(bpy.data.collections):
    if c.name.startswith('export'):
        for o in list(c.objects): bpy.data.objects.remove(o, do_unlink=True)
        bpy.data.collections.remove(c)
M = {m.name: m for m in bpy.data.materials if m.library}
image = bpy.data.images.load(str(OUT/'sign_atlas.png'), check_existing=False)
image.name = 'al_paso_atlas'; image.pack()
mat = bpy.data.materials.new('mat_al_paso_atlas'); mat.use_nodes = True
bs = mat.node_tree.nodes.get('Principled BSDF'); bs.inputs['Roughness'].default_value = .8
tex = mat.node_tree.nodes.new('ShaderNodeTexImage'); tex.image = image
mat.node_tree.links.new(tex.outputs['Color'], bs.inputs['Base Color'])
M['atlas'] = mat
swatches = ['navy','paper','sweet','hot','salt','oil','potato']
C = None; root = None

def empty(name, pos=(0,0,0), parent=None):
    o = bpy.data.objects.new(name, None); C.objects.link(o); o.location=pos; o.parent=parent
    return o

def begin(name, collection):
    global C, root
    C=bpy.data.collections.new(collection); bpy.context.scene.collection.children.link(C)
    root=empty(name)
    empty('Anchor_Front' if name=='seasoning_station' else 'Anchor_Front_'+name, (0,.56,0), root)

def finish(o, name, material):
    o.name=name
    for c in list(o.users_collection): c.objects.unlink(o)
    C.objects.link(o); o.parent=root
    bpy.context.view_layer.objects.active=o
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
    o.data.materials.clear(); o.data.materials.append(M.get(material,M['atlas']))
    uv=o.data.uv_layers.active or o.data.uv_layers.new()
    for p in o.data.polygons:
        axis=max(range(3),key=lambda i:abs(p.normal[i]))
        for li in p.loop_indices:
            v=o.data.vertices[o.data.loops[li].vertex_index].co
            uv.data[li].uv=((swatches.index(material)*64+32)/512, 1-32/512) if material in swatches else ((v.y/2,v.z/2),(v.x/2,v.z/2),(v.x/2,v.y/2))[axis]
    return o

def cube(name,p,s,material,bevel=.02):
    bpy.ops.mesh.primitive_cube_add(size=1,location=p); o=bpy.context.object; o.dimensions=s
    bpy.ops.object.transform_apply(location=False,rotation=False,scale=True)
    if bevel:
        mod=o.modifiers.new('Soft edges','BEVEL');mod.width=bevel;mod.segments=2
        bpy.ops.object.modifier_apply(modifier=mod.name)
    return finish(o,name,material)

def cyl(name,p,r,h,material,n=24,rot=0):
    bpy.ops.mesh.primitive_cylinder_add(vertices=n,radius=r,depth=h,location=p,rotation=(rot,0,0))
    return finish(bpy.context.object,name,material)

def mesh(name,verts,faces,material):
    d=bpy.data.meshes.new(name);d.from_pydata(verts,[],faces);d.update()
    o=bpy.data.objects.new(name,d);C.objects.link(o)
    return finish(o,name,material)

def join(parts,name):
    bpy.ops.object.select_all(action='DESELECT')
    for o in parts:o.select_set(True)
    bpy.context.view_layer.objects.active=parts[0];bpy.ops.object.join();parts[0].name=name
    return parts[0]

def icon(name,p,kind,size=.22):
    # Opaque atlas tile, baked on the button face inclined toward the service side.
    a=math.radians(52); u=Vector((1,0,0));v=Vector((0,math.cos(a),math.sin(a)));center=Vector(p)
    o=mesh(name,[center+u*x*size/2+v*y*size/2 for x,y in [(-1,-1),(1,-1),(1,1),(-1,1)]],[(0,1,2,3)],'atlas')
    col,row={'sweet':(0,1),'hot':(1,1),'salt':(2,1),'oil':(3,1),'potato':(0,2)}[kind]
    for li,(x,y) in enumerate([(0,0),(1,0),(1,1),(0,1)]):o.data.uv_layers.active.data[li].uv=((col*128+x*128)/512,1-((row+1)*128-y*128)/512)
    return o

def button(x,y,z,kind):
    a=math.radians(52); normal=Vector((0,-math.sin(a),math.cos(a)))
    p=Vector((x,y,z)); parts=[cyl('ButtonRim',p,.161,.018,'navy',32,a),cyl('PaperButton',p+normal*.012,.15,.012,'paper',32,a)]
    parts.append(icon('ButtonIcon',p+normal*.020,kind))
    return parts

begin('seasoning_station','export')
cube('counter',(0,0,1.04),(5.1,1.1,.12),'mat_steel_brushed_top')
cube('ServiceFascia',(0,-.545,.85),(5.06,.045,.24),'navy')
cube('KitchenRail',(0,.52,.86),(5.02,.05,.16),'mat_steel_brushed_mid')
cube('Shelf',(0,0,.23),(4.95,.93,.06),'mat_steel_brushed_mid')
for x in [-2.43,2.43]:
    for y in [-.43,.43]:cube('Leg',(x,y,.51),(.10,.10,1.02),'mat_steel_brushed_mid',.012)
# A flat service mat is visual only; no new collision geometry.
cube('ServiceMat',(0,-.95,.008),(5.04,.56,.016),'navy',.008)
for i,kind in enumerate(['sweet','hot','salt','oil','potato']):
    x=i-2
    cube('IngredientStripe',(x,-.573,.85),(.56,.008,.14),kind,.006)
    # Broad chevrons point from the counter into service, not onto a tray slot.
    verts=[(x-.16,-.23,1.102),(x,-.39,1.102),(x+.16,-.23,1.102),(x+.11,-.18,1.102),(x,-.29,1.102),(x-.11,-.18,1.102)]
    mesh('ServiceChevron',[(vx,vy-.68,.018) for vx,vy,vz in verts],[(0,1,4,5),(1,2,3,4)],'paper')
    empty(['Anchor_Dispenser_SweetPaprika','Anchor_Dispenser_HotPaprika','Anchor_Dispenser_Salt','Anchor_Dispenser_Oil','Anchor_Bowl'][i],(x,0,1.1),root)
empty('Anchor_OperatorSide',(0,-1.2,0),root);empty('Anchor_PassSide',(0,1.2,0),root)
# Sweet and hot read as a pair, joined with a narrow painted strip.
cube('PaprikaPair',(-1.5,-.07,1.101),(1.56,.045,.002),'paper',0)

begin('seasoning_dispenser','export_dispenser')
for kind,name in [('sweet','paprika_sweet'),('hot','paprika_hot'),('salt','salt'),('oil','oil')]:
    start=set(C.objects)
    if kind=='sweet':
        cyl('WideTin',(0,0,.08),.175,.16,kind,32)
        cyl('TinLip',(0,0,.163),.18,.015,'mat_steel_brushed_mid',32)
    elif kind=='hot':
        cyl('FacetedTin',(0,0,.105),.115,.21,kind,8)
        cyl('TinLip',(0,0,.213),.12,.014,'mat_steel_dark',8)
    elif kind=='salt':
        cyl('Shaker',(0,0,.08),.14,.16,kind,16)
        cyl('DarkCap',(0,0,.18),.15,.045,'mat_steel_dark',16)
    else:
        cyl('Bottle',(0,0,.075),.095,.15,kind,16)
        cyl('Neck',(0,0,.185),.055,.075,kind,16)
        cyl('SpoutBase',(0,0,.225),.06,.025,'mat_steel_dark',16)
        cube('PouringSpout',(.115,0,.239),(.23,.045,.022),'mat_steel_dark',.006)
    button(0,-.40,.125,kind)
    join(list(set(C.objects)-start),name)

begin('cachelos_bowl','export_bowl')
# Closed wall volume with open cavity: outer wall, thick rim, inner wall and floor.
N=24; profile=[(.16,0),(.245,.15),(.225,.175),(.20,.15),(.135,.04),(0,.04),(0,0)]
verts=[(r*math.cos(i*2*math.pi/N),r*math.sin(i*2*math.pi/N),z) for r,z in profile for i in range(N)]
faces=[]
for j in range(len(profile)-1):
    for i in range(N):faces.append((j*N+i,j*N+(i+1)%N,(j+1)*N+(i+1)%N,(j+1)*N+i))
mesh('bowl',verts,faces,'mat_clay')
join(button(0,-.39,.125,'potato'),'BowlButton')
empty('Anchor_Portions',(0,0,.07),root)
for count in range(5):
    parts=[]
    # Empty state has a clay floor, not a zero-triangle placeholder.
    parts.append(cyl('Floor',(0,0,.041),.13,.003,'mat_clay',16))
    for i in range(count):
        x,y=[(-.083,-.07),(.083,.06),(-.083,.07),(.083,-.07)][i]
        bpy.ops.mesh.primitive_ico_sphere_add(subdivisions=1,radius=1,location=(x,y,.11))
        o=bpy.context.object;o.scale=(.075,.066,.065)
        parts.append(finish(o,'Potato','mat_food_potato_cooked'))
    join(parts,'Portions'+str(count))
# Dedicated closed hull. PUL-097 binds Highlightable.root here as in existing bowl scene.
hullroot=empty('OutlineHull',parent=root)
hull=cyl('BowlHull',(0,0,.079),.234,.158,'paper',16);hull.parent=hullroot
invisible=bpy.data.materials.new('mat_outline_proxy');invisible.use_nodes=True
bs=invisible.node_tree.nodes.get('Principled BSDF');bs.inputs['Alpha'].default_value=0
invisible.surface_render_method='DITHERED';hull.data.materials.clear();hull.data.materials.append(invisible)

# Triangulate explicitly for reliable tangents on ngon caps.
for collection in [c for c in bpy.data.collections if c.name.startswith('export')]:
    for obj in collection.objects:
        if obj.type == 'MESH':
            bm=bmesh.new();bm.from_mesh(obj.data)
            bmesh.ops.triangulate(bm, faces=list(bm.faces))
            bm.to_mesh(obj.data);bm.free()
# Save source with linked library paths relative and packed custom atlas.
bpy.context.preferences.filepaths.save_version=0
bpy.ops.wm.save_as_mainfile(filepath=str(ROOT/'art/blender/seasoning_station.blend'))
# Run the repository validator/exporter for each collection without altering saved source.
source=(ROOT/'tools/blender_export.py').read_text();source=source.rsplit('\nmain()',1)[0]
ns={'__file__':str(ROOT/'tools/blender_export.py')};exec(compile(source,'blender_export.py','exec'),ns)
counts={}
for coll,name in [('export','seasoning_station'),('export_dispenser','seasoning_dispenser'),('export_bowl','cachelos_bowl')]:
    ns['EXPORT_COLLECTION']=coll
    anchors=[o for o in bpy.data.collections[coll].objects if o.name.startswith('Anchor_Front')]
    old=anchors[0].name
    other=bpy.data.objects.get('Anchor_Front')
    if other and other!=anchors[0]:other.name='StationFrontTemporary'
    anchors[0].name='Anchor_Front'
    counts[name]=ns['validate'](ns['collection_objects'](),6000)
    ns['select_export_collection']()
    bpy.ops.export_scene.gltf(filepath=str(DEST/(name+'.glb')),export_format='GLB',use_active_collection=True,use_active_collection_with_nested=True,use_visible=False,export_yup=True,export_apply=True,export_cameras=False,export_lights=False,export_extras=False,export_materials='EXPORT',export_image_format='AUTO',export_tangents=True,export_animations=False,export_skins=False,export_morph=False)
    anchors[0].name=old
    if other and other!=anchors[0]:other.name='Anchor_Front'
counts['total_all_variants_all_portions']=sum(counts.values())
assert counts['total_all_variants_all_portions']<=6000,counts
(OUT/'triangles.json').write_text(json.dumps(counts,indent=2)+'\n')
print('PUL094_BUDGET',counts)
